module.exports = {
    async create(pool) {
        // Main table for inventory items (core fields)
        await pool.query(`
      CREATE TABLE IF NOT EXISTS inventory_items (
       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        stock INTEGER DEFAULT 0,
        min_stock INTEGER DEFAULT 0,
        buy_price NUMERIC(12, 2) DEFAULT 0,
        sale_price NUMERIC(12, 2) DEFAULT 0,
        barcode TEXT,
        sold INTEGER DEFAULT 0,
        created_at TIMESTAMP DEFAULT NOW(),
        updated_at TIMESTAMP DEFAULT NOW()
      );
    `);

        // Flexible field metadata table (for user-added custom fields)
        await pool.query(`
      CREATE TABLE IF NOT EXISTS inventory_item_metadata (
        item_id INTEGER NOT NULL REFERENCES inventory_items(id) ON DELETE CASCADE,
        field_name TEXT NOT NULL,
        field_value TEXT,
        PRIMARY KEY (item_id, field_name)
      );
    `);

        // Indexes for standard inventory fields
        await pool.query(`CREATE INDEX IF NOT EXISTS idx_inventory_name ON inventory_items(name);`);
        await pool.query(`CREATE INDEX IF NOT EXISTS idx_inventory_barcode ON inventory_items(barcode);`);
        await pool.query(`CREATE INDEX IF NOT EXISTS idx_inventory_stock ON inventory_items(stock);`);

        // Indexes for metadata searching
        await pool.query(`CREATE INDEX IF NOT EXISTS idx_metadata_field_name ON inventory_item_metadata(field_name);`);
        await pool.query(`CREATE INDEX IF NOT EXISTS idx_metadata_field_value ON inventory_item_metadata(field_value);`);
    }
};
