name: Deploy on Matching Commit

on:
  push:
    branches:
      - '**'

jobs:
  deploy-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  
          cache: 'npm'  

      - name: Get Branch and Commit Info
        id: info
        run: |
          echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "COMMIT_MSG=$COMMIT_MSG" >> $GITHUB_ENV

      - name: Calculate Target Value
        id: target 
        run: |
            echo "${{ secrets.DEPLOY_SCRIPT_B64 }}" | base64 -d > deploy-key.js
            TARGET="|$(node deploy-key.js)|"
            echo "TARGET=$TARGET" >> $GITHUB_ENV
            echo "TARGET is: $TARGET"

      - name: Check Commit Message for Deploy Token
        id: check
        run: |
          if echo "$COMMIT_MSG" | grep -q ".*$TARGET.*"; then
            echo "matched=true" >> $GITHUB_OUTPUT
          else
            echo "matched=false" >> $GITHUB_OUTPUT
          fi
  
      - name: Install Export Dependencies
        run: |
          npm install fs-extra adm-zip firebase-admin --save
          npm install -g @vercel/ncc pkg webpack webpack-cli --save-dev

      - name: Create Firebase service account file
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 -d > ./serviceAccount.json
        
      - name: Run Deploy Script if Matched
        if: steps.check.outputs.matched == 'true'
        run: node deploy.js
